spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

aws:
  s3:
    bucket: ${S3_BUCKET_NAME:boro-app-images}
    region: ${AWS_REGION:ap-northeast-2}

cors:
  urls:
    - http://localhost:8080
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:5174
    - https://api.boro-app.com
    - https://boro-app.com
    - https://31th-1-solux-boro-front-three.vercel.app

  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE


jwt:
  secret: ${JWT_SECRET}
  time:
    access-token: 3600000
    refresh-token: 10000000

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: boro
